const mongoose = require('mongoose');

const transactionSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  merchantName: String,
  merchantId: String,
  transactionId: String,
  orderId: String,
  status: String,
  clientName: String,
  clientEmail: String,
  clientPhone: String,
  clientVPA: String,
  amount: Number,
  gst: Number,
  tds: Number,
  totalAmount: Number,
  netAmount: Number,
  settlementAmount: Number,
  settledAmount: Number,
  initiatedAt: Date,
  completedAt: Date,
  settled: Boolean,
  settlementBatch: String,
  settledAt: Date,
  refunded: Boolean,
  refundedAt: Date,
  paymentMethod: String,
  paymentSource: String,
  vpa: String,
  pgReference: String,
  utrNumber: String,
  message: String,
  sourceType: String,
  isFlagged: Boolean,
  flaggedReason: String,
  disputeStatus: String,
  disputeNote: String,
  reasonCode: String,
  mccCode: String,
  uploadedAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Transaction', transactionSchema);
